name: lar3n
favicon: null
layout_spectrum: 0.015266892733052373
typography_spectrum: 0.28669302142225206
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8829908985644579
  lightness: 0.21451588673517108
  saturation: 0.8231833826284856
  rhythmicContrast: 0.01519507123157382
purpose: []
