name: lar3n Music
favicon: null
layout_spectrum: 0.99833
typography_spectrum: 0.16148
title: lar3n Music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0e9de'
    - '#b0b4ae'
    - '#1f1116'
    - '#929690'
    - '#707070'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
