name: lar3n
favicon: null
layout_spectrum: 1
typography_spectrum: 0.22325
title: lar3n.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.875
  lightness: 0.21451588673517108
  saturation: 0.8231833826284856
  rhythmicContrast: 0.01519507123157382
purpose: []
