name: lar3n Music
favicon: null
layout_spectrum: 0.95993
typography_spectrum: 0.22325
title: lar3n Music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#949494'
    - '#ffffff'
    - '#3b3b3b'
    - '#4c150b'
  brandStrength: 0.875
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
