name: lar3n Music
favicon: null
layout_spectrum: 0
typography_spectrum: 0.12976
title: lar3n
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0e9de'
    - '#b0b4ae'
    - '#1f1116'
    - '#929690'
    - '#707070'
  brandStrength: 0.25
  lightness: 0
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
